# Generated by Django 2.2.6 on 2023-08-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa_reservation', '0002_availability_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatePricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='guest_numbers',
            new_name='adult_numbers',
        ),
        migrations.AddField(
            model_name='reservation',
            name='children_numbers',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
