# Generated by Django 4.2.4 on 2023-09-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa_reservation', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
