# Generated by Django 4.2.4 on 2023-09-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa_reservation', '0009_remove_review_user_id_review_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
