version: '3.8'
services:
  reservation-service:
    image: reservation-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - "database"
  
  database:
    image: mysql:latest
    restart: always
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservation
      MYSQL_USER: amine
      MYSQL_PASSWORD: 1234
    volumes:
      - .dbdata:/var/lib/mysql