version: '3.8'
services:
  reservation-service:
    image: reservation-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - "database_reservation"
    networks:
      - authentication_microservice_villa-net
  database_reservation:
    image: mysql:latest
    restart: always
    ports:
      - "33066:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservation
      MYSQL_USER: amine
      MYSQL_PASSWORD: 1234
    volumes:
      - .dbdata:/var/lib/mysql
    networks:
      - authentication_microservice_villa-net
networks:
  authentication_microservice_villa-net:
    external: true