version: '3.8'
services:
  payment-service:
    image: payment-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - .:/app
    depends_on:
      - "database_payment"
    networks:
      - authentication_microservice_villa-net
  database_payment:
    image: mysql:latest
    restart: always
    ports:
      - "33068:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment
      MYSQL_USER: amine
      MYSQL_PASSWORD: 1234
    volumes:
      - .dbdata:/var/lib/mysql
    networks:
      - authentication_microservice_villa-net
networks:
  authentication_microservice_villa-net:
    external: true